"""Diagnose input-space vs hazard-space coverage on the input-spanning masters.

Decision-gating diagnostic for the hazard-filling contribution. From each richness-ladder master
(generated by ``generate_input_spanning_master.py``) it forms three size-N subsets with the SAME
LHS+nearest-neighbor selector applied in different spaces:

  - ``input_stratified`` -- space-filling in INPUT (forcing-parameter) space (theta),
  - ``hazard_filling``    -- space-filling in HAZARD space (the 4 screened axes),
  - ``random``            -- random-without-replacement baseline,

then quantifies, in BOTH spaces, coverage (L2-star discrepancy, NN-CV, MST mean) and a kernel
effective-sample-size (ESS) redundancy measure. Because all three subsample the *same* theta-spanning
master, any hazard-coverage difference is attributable to the selection criterion, not the generator.

The richness ladder (``mean_only`` vs ``mean_var``) tests whether the input!=hazard gap is a generic
mechanism or an artifact of an impoverished (mean-only) input space: the premise is credible only if
the gap persists under the enriched input space.

Outputs to ``outputs/diagnostics/input_vs_hazard_coverage/``: ``results.json``, ``figures/*.png``,
``FINDINGS.md``.

Run from the repo root::

    PYTHONPATH=$(pwd -W) venv/Scripts/python.exe scripts/supplemental/diagnose_input_vs_hazard_coverage.py
"""

from __future__ import annotations

import json
import os
from pathlib import Path

import numpy as np
from scipy.stats import spearmanr

import config
from src.ensembles import staged_ensemble_dir
from src.load.historical_flows import load_historical_flows

from scengen.diagnostics import (
    expected_random_discrepancy,
    hazard_effective_sample_size,
    mst_mean_edge,
)
from scengen.hazard_filling import (
    daily_to_monthly,
    load_ensemble_daily_aggregate,
    load_ensemble_monthly_aggregate,
)
from scengen.hazard_metrics import DEFAULT_NYC_INFLOW_NODES, compute_candidate_hazard_image
from scengen.subsample import (
    coverage_metrics,
    empirical_cdf_normalize,
    hazard_filling_subsample,
    input_stratified_subsample,
    random_subsample,
)

REALIZATION_YEARS = 5
FIXED_AXES = (
    "drought_deficit_volume",
    "drought_onset_rate",
    "flood_peak_magnitude",
    "flood_pulse_duration",
)
N_SWEEP = (32, 64, 128)
SUBSET_SEEDS = tuple(range(5))
N_BOOT = 500
DESIGNS = ("input_stratified", "hazard_filling", "random")
DESIGN_COLORS = {
    "input_stratified": "#1f77b4",
    "hazard_filling": "#d62728",
    "random": "#7f7f7f",
}
OUT_DIR = config.OUTPUTS_DIR / "diagnostics" / "input_vs_hazard_coverage"


# ---------------------------------------------------------------------------
# Loading
# ---------------------------------------------------------------------------

def _select_indices(design, matrix_hazard, Theta, n, seed):
    """Return n selected row indices for a design (selection space differs by design)."""
    if design == "input_stratified":
        return input_stratified_subsample(Theta, n, seed=seed)
    if design == "hazard_filling":
        return hazard_filling_subsample(matrix_hazard, n, seed=seed)
    if design == "random":
        return random_subsample(matrix_hazard, n, seed=seed)
    raise ValueError(design)


def load_rung(slug, reference_monthly, reference_daily):
    """Load a master, compute its hazard image (4 fixed axes) and input coordinates theta."""
    pool_dir = staged_ensemble_dir(slug)
    pool_hdf5 = pool_dir / "catchment_inflow_mgd.hdf5"
    if not pool_hdf5.exists():
        raise FileNotFoundError(f"master not staged: {pool_hdf5}")

    scenario_monthly, realization_ids = load_ensemble_monthly_aggregate(
        pool_hdf5, DEFAULT_NYC_INFLOW_NODES, agg="mean"
    )
    scenario_daily, _ = load_ensemble_daily_aggregate(pool_hdf5, DEFAULT_NYC_INFLOW_NODES)

    H_all, axes_all = compute_candidate_hazard_image(
        scenario_monthly, scenario_daily, reference_monthly, reference_daily
    )
    col = {a: i for i, a in enumerate(axes_all)}
    missing = [a for a in FIXED_AXES if a not in col]
    if missing:
        raise KeyError(f"fixed axes missing from hazard image: {missing}")
    H4 = H_all[:, [col[a] for a in FIXED_AXES]]

    npz = np.load(pool_dir / "forcing_profiles.npz", allow_pickle=True)
    a = npz["mean_factor_a"].astype(float)
    if "cv_factor_v" in npz:
        Theta = np.hstack([a, npz["cv_factor_v"].astype(float)])
    else:
        Theta = a
    return {
        "slug": slug,
        "H4": H4,
        "Theta": Theta,
        "a": a,
        "scenario_monthly": scenario_monthly,
        "n_master": H4.shape[0],
    }


# ---------------------------------------------------------------------------
# Coverage analysis
# ---------------------------------------------------------------------------

def _subset_coverage(Xnorm, sel, baseline_samples):
    """Coverage metrics for one subset in a CDF-normalized space."""
    d = Xnorm.shape[1]
    n = len(sel)
    cm = coverage_metrics(Xnorm[sel], np.zeros(d), np.ones(d))
    l2 = cm["L2_star_discrepancy"]
    ess = hazard_effective_sample_size(Xnorm[sel])  # default discriminating bandwidth
    pct = float(np.mean(baseline_samples <= l2)) if baseline_samples is not None else float("nan")
    return {
        "l2_star": l2,
        "nn_cv": cm.get("nn_cv", float("nan")),
        "nn_min": cm.get("nn_min", float("nan")),
        "mst_mean": mst_mean_edge(Xnorm[sel]),
        "ess": ess["ess"],
        "ess_fraction": ess["ess_fraction"],
        "discrepancy_percentile": pct,
    }


def _agg(records):
    """Mean/std over seed replicates for each metric."""
    keys = records[0].keys()
    out = {}
    for k in keys:
        vals = np.array([r[k] for r in records], dtype=float)
        out[f"{k}_mean"] = float(np.nanmean(vals))
        out[f"{k}_std"] = float(np.nanstd(vals))
    return out


def analyze_rung(rung):
    """Coverage + ESS in hazard and input space across designs, N, seeds."""
    H4, Theta = rung["H4"], rung["Theta"]
    M = rung["n_master"]
    spaces = {
        "hazard": (H4, empirical_cdf_normalize(H4)),
        "input": (Theta, empirical_cdf_normalize(Theta)),
    }
    n_sweep = [n for n in N_SWEEP if n < M] or [max(4, M // 4), max(8, M // 2)]

    results = {"n_master": M, "n_sweep": n_sweep, "spaces": {}}
    for space_name, (_, Xnorm) in spaces.items():
        d = Xnorm.shape[1]
        results["spaces"][space_name] = {"dimensions": d, "by_n": {}}
        for n in n_sweep:
            base = expected_random_discrepancy(n, d, n_boot=N_BOOT, seed=0, pool_X=Xnorm)
            base_samples = np.asarray(base["samples"], dtype=float)
            per_design = {}
            for design in DESIGNS:
                recs = [
                    _subset_coverage(
                        Xnorm, _select_indices(design, H4, Theta, n, s), base_samples
                    )
                    for s in SUBSET_SEEDS
                ]
                per_design[design] = _agg(recs)
            per_design["_random_baseline_l2"] = {
                "mean": float(base["mean"]), "std": float(base["std"])
            }
            results["spaces"][space_name]["by_n"][n] = per_design
    return results


def reachability(rung):
    """How far the input space moves each hazard axis (max |Spearman| over input columns)."""
    H4, Theta = rung["H4"], rung["Theta"]
    out = {}
    for j, axis in enumerate(FIXED_AXES):
        rs = [abs(spearmanr(Theta[:, k], H4[:, j]).statistic) for k in range(Theta.shape[1])]
        out[axis] = {"max_abs_spearman": float(np.nanmax(rs))}
    return out


# ---------------------------------------------------------------------------
# Figures
# ---------------------------------------------------------------------------

def _pca_2d(X):
    Xc = X - X.mean(0)
    U, S, Vt = np.linalg.svd(Xc, full_matrices=False)
    return Xc @ Vt[:2].T, Vt[:2]


def make_figures(rungs, results, style, fig_dir):
    import matplotlib.pyplot as plt

    fig_dir.mkdir(parents=True, exist_ok=True)
    enriched = rungs.get("mean_var", next(iter(rungs.values())))

    # F1/F2 forcing profiles + F3 PC scatter (use the enriched master's a, v).
    mean_env = _load_mean_envelope()
    _fig_forcing_profiles(enriched, mean_env, style, fig_dir, plt)
    # F4 example hydrographs.
    _fig_hydrographs(enriched, style, fig_dir, plt)

    for rung_name, rung in rungs.items():
        res = results[rung_name]["coverage"]
        _fig_space_scatter(rung, "hazard", style, fig_dir, plt, rung_name)
        _fig_space_scatter(rung, "input", style, fig_dir, plt, rung_name)
        _fig_metric_vs_n(res, "hazard", "l2_star", "L2-star discrepancy (hazard space)",
                         style, fig_dir, plt, rung_name)
        _fig_metric_vs_n(res, "hazard", "ess", "Hazard ESS", style, fig_dir, plt, rung_name)
        _fig_input_to_hazard_map(rung, results[rung_name]["reachability"], style, fig_dir, plt, rung_name)


def _load_mean_envelope():
    from scengen import forcing_space as fs
    csv = (Path(config.PROJECT_DIR).parent / "CMIP6_multimodel_streamflow" / "stats"
           / "diff_relative_to_dataset_baseline"
           / "nyc_inflow_monthly_mean_frac_by_dataset_ssp_and_period.csv")
    return fs.load_cmip6_envelope(csv)


def _fig_forcing_profiles(rung, mean_env, style, fig_dir, plt):
    a = rung["a"]
    months = np.arange(1, 13)
    fig, ax = plt.subplots(figsize=(7, 4))
    ax.plot(months, mean_env.values, color="0.6", lw=0.6, alpha=0.5)
    ax.plot(months, a[:: max(1, len(a) // 200)].T, color="#1f77b4", lw=0.4, alpha=0.3)
    ax.fill_between(months, mean_env.values.min(1), mean_env.values.max(1),
                    color="0.8", alpha=0.4, label="CMIP6 envelope")
    ax.plot(months, mean_env.values.mean(1), color="k", lw=2, label="CMIP6 mean")
    ax.set(xlabel="Month (water-year order)", ylabel="Mean change factor $a_j$",
           title="F1. Sampled mean change-factor profiles vs CMIP6 anchors")
    ax.legend(fontsize=8)
    style.save_figure(fig, fig_dir / "F1_mean_change_profiles")
    plt.close(fig)

    if rung["Theta"].shape[1] > 12:
        v = rung["Theta"][:, 12:]
        fig, ax = plt.subplots(figsize=(7, 4))
        ax.plot(months, v[:: max(1, len(v) // 200)].T, color="#d62728", lw=0.4, alpha=0.3)
        ax.axhline(1.0, color="k", lw=1, ls="--", label="CV-preserving ($v_j=1$)")
        ax.set(xlabel="Month (water-year order)", ylabel="CV change factor $v_j$",
               title="F2. Sampled CV (variance) change-factor profiles")
        ax.legend(fontsize=8)
        style.save_figure(fig, fig_dir / "F2_cv_change_profiles")
        plt.close(fig)

    # F3 PC scatter: anchors vs sampled (mean space, log).
    anchors = np.log(mean_env.values.T)
    samp = np.log(rung["a"])
    mu = anchors.mean(0)
    _, _, Vt = np.linalg.svd(anchors - mu, full_matrices=False)
    sa = (anchors - mu) @ Vt[:2].T
    ss = (samp - mu) @ Vt[:2].T
    fig, ax = plt.subplots(figsize=(5.5, 5))
    ax.scatter(ss[:, 0], ss[:, 1], s=6, alpha=0.3, color="#1f77b4", label="sampled $\\theta$")
    ax.scatter(sa[:, 0], sa[:, 1], s=40, color="k", marker="x", label="CMIP6 anchors")
    ax.set(xlabel="PC1", ylabel="PC2", title="F3. Forcing draws vs CMIP6 anchors (PC space)")
    ax.legend(fontsize=8)
    style.save_figure(fig, fig_dir / "F3_forcing_pc_scatter")
    plt.close(fig)


def _fig_hydrographs(rung, style, fig_dir, plt):
    sm = rung["scenario_monthly"]
    nm = sm.shape[1] - sm.shape[1] % 12
    cycle = sm[:, :nm].reshape(sm.shape[0], -1, 12).mean(1)  # mean annual cycle per realization
    order = np.argsort(sm.mean(1))
    picks = {"dry (10th pct)": order[len(order) // 10],
             "median": order[len(order) // 2],
             "wet (90th pct)": order[9 * len(order) // 10]}
    months = np.arange(1, 13)
    fig, ax = plt.subplots(figsize=(7, 4))
    for label, idx in picks.items():
        ax.plot(months, cycle[idx], lw=2, label=label)
    ax.plot(months, cycle.mean(0), color="k", lw=1.5, ls="--", label="master mean")
    ax.set(xlabel="Month (water-year order)", ylabel="Mean NYC inflow (MGD)",
           title="F4. Example realized annual cycles (climate-adjusted)")
    ax.legend(fontsize=8)
    style.save_figure(fig, fig_dir / "F4_example_hydrographs")
    plt.close(fig)


def _fig_space_scatter(rung, space, style, fig_dir, plt, rung_name):
    X = rung["H4"] if space == "hazard" else rung["Theta"]
    Xn = empirical_cdf_normalize(X)
    P, _ = _pca_2d(Xn)
    n = _headline_n(rung["n_master"])
    fig, ax = plt.subplots(figsize=(6, 5.5))
    ax.scatter(P[:, 0], P[:, 1], s=5, color="0.8", alpha=0.5, label="master")
    for design in DESIGNS:
        sel = _select_indices(design, rung["H4"], rung["Theta"], n, 0)
        ax.scatter(P[sel, 0], P[sel, 1], s=22, alpha=0.85,
                   color=DESIGN_COLORS[design], label=design, edgecolor="white", linewidth=0.3)
    ax.set(xlabel="PC1", ylabel="PC2",
           title=f"{'F5' if space=='hazard' else 'F6'}. {space.title()}-space coverage "
                 f"(N={n}, {rung_name})")
    ax.legend(fontsize=8, markerscale=1.2)
    tag = "F5_hazard_scatter" if space == "hazard" else "F6_input_scatter"
    style.save_figure(fig, fig_dir / f"{tag}_{rung_name}")
    plt.close(fig)


def _fig_metric_vs_n(res, space, metric, ylabel, style, fig_dir, plt, rung_name):
    by_n = res["spaces"][space]["by_n"]
    ns = sorted(by_n)
    fig, ax = plt.subplots(figsize=(6, 4.5))
    for design in DESIGNS:
        means = [by_n[n][design][f"{metric}_mean"] for n in ns]
        stds = [by_n[n][design][f"{metric}_std"] for n in ns]
        ax.errorbar(ns, means, yerr=stds, marker="o", capsize=3,
                    color=DESIGN_COLORS[design], label=design)
    if metric == "l2_star":
        rb = [by_n[n]["_random_baseline_l2"]["mean"] for n in ns]
        ax.plot(ns, rb, color="k", ls=":", lw=1, label="random baseline (bootstrap)")
    ax.set(xlabel="Subset size N", ylabel=ylabel,
           title=f"{'F7' if metric=='l2_star' else 'F8'}. {ylabel} ({rung_name})")
    ax.set_xticks(ns)
    ax.legend(fontsize=8)
    tag = "F7_l2_vs_n" if metric == "l2_star" else "F8_ess_vs_n"
    style.save_figure(fig, fig_dir / f"{tag}_{space}_{rung_name}")
    plt.close(fig)


def _fig_input_to_hazard_map(rung, reach, style, fig_dir, plt, rung_name):
    P, _ = _pca_2d(empirical_cdf_normalize(rung["Theta"]))
    fig, axes = plt.subplots(2, 2, figsize=(10, 8.5), constrained_layout=True)
    for ax, axis in zip(axes.ravel(), FIXED_AXES):
        vals = rung["H4"][:, FIXED_AXES.index(axis)]
        sc = ax.scatter(P[:, 0], P[:, 1], c=vals, s=8, cmap="viridis")
        fig.colorbar(sc, ax=ax, shrink=0.8)
        r = reach[axis]["max_abs_spearman"]
        ax.set(xlabel="input PC1", ylabel="input PC2",
               title=f"{axis}\nmax|Spearman(theta, axis)|={r:.2f}")
    fig.suptitle(f"F9. Input space -> hazard distribution ({rung_name})", fontsize=12)
    style.save_figure(fig, fig_dir / f"F9_input_to_hazard_map_{rung_name}")
    plt.close(fig)


def _headline_n(M):
    valid = [n for n in N_SWEEP if n < M]
    if not valid:
        return max(4, M // 2)
    return 64 if 64 in valid else max(valid)


# ---------------------------------------------------------------------------
# Verdict + memo
# ---------------------------------------------------------------------------

def compute_headline(results, rungs):
    """Discrepancy ratio / percentiles / ESS (hazard-filling vs input-stratified) at the headline N.

    The primary signal is the hazard-space L2-star discrepancy and its percentile against the random
    baseline at matched N (lower discrepancy / lower percentile = more uniform coverage). ESS is a
    corroborating-but-weak redundancy summary.
    """
    head = {}
    for rung_name, rung in rungs.items():
        n = _headline_n(rung["n_master"])
        haz = results[rung_name]["coverage"]["spaces"]["hazard"]["by_n"][n]
        inp = results[rung_name]["coverage"]["spaces"]["input"]["by_n"][n]
        l2_hf = haz["hazard_filling"]["l2_star_mean"]
        l2_is = haz["input_stratified"]["l2_star_mean"]
        head[rung_name] = {
            "headline_n": n,
            "hazard_l2_ratio_input_over_hazfill": l2_is / l2_hf if l2_hf else float("nan"),
            "hazard_pctile_hazard_filling": haz["hazard_filling"]["discrepancy_percentile_mean"],
            "hazard_pctile_input_stratified": haz["input_stratified"]["discrepancy_percentile_mean"],
            "hazard_ess_hazard_filling": haz["hazard_filling"]["ess_mean"],
            "hazard_ess_input_stratified": haz["input_stratified"]["ess_mean"],
            "hazard_ess_gap": haz["hazard_filling"]["ess_mean"] - haz["input_stratified"]["ess_mean"],
            "hazard_nn_cv_input_stratified": haz["input_stratified"]["nn_cv_mean"],
            "hazard_nn_cv_hazard_filling": haz["hazard_filling"]["nn_cv_mean"],
            "input_l2_input_stratified": inp["input_stratified"]["l2_star_mean"],
            "input_l2_hazard_filling": inp["hazard_filling"]["l2_star_mean"],
        }
    return head


def verdict(head, results, rungs):
    """Nuanced verdict, judged at the enriched (fair-test) rung.

    Anchored on hazard-space L2 discrepancy: does hazard-filling cover hazard space markedly better
    than input-space LHS, and does that advantage survive enriching the input space (the fair test)?
    """
    key = "mean_var" if "mean_var" in head else next(iter(head))
    h = head[key]
    ratio = h["hazard_l2_ratio_input_over_hazfill"]
    pct_hf = h["hazard_pctile_hazard_filling"]
    pct_is = h["hazard_pctile_input_stratified"]
    mirror_ok = h["input_l2_input_stratified"] < h["input_l2_hazard_filling"]
    hf_beats_random = pct_hf < 0.15           # hazard-filling reliably better than random
    input_redundant = pct_is > 0.35           # input-LHS no better than random in hazard space

    # How much of the impoverished-rung redundancy was an input-poverty artifact.
    artifact_fraction = float("nan")
    if "mean_only" in head and "mean_var" in head:
        r_imp = head["mean_only"]["hazard_l2_ratio_input_over_hazfill"]
        r_enr = head["mean_var"]["hazard_l2_ratio_input_over_hazfill"]
        if r_imp > 1:
            artifact_fraction = (r_imp - r_enr) / (r_imp - 1.0)

    if hf_beats_random and ratio >= 1.5 and input_redundant and mirror_ok:
        v = "HOLDS (strong)"
    elif hf_beats_random and ratio >= 1.2 and mirror_ok:
        v = "HOLDS (moderate)"
    elif hf_beats_random and ratio >= 1.05:
        v = "WEAK"
    else:
        v = "FAILS"
    return {
        "verdict": v, "judged_rung": key, "discrepancy_ratio": ratio,
        "hazard_filling_percentile": pct_hf, "input_stratified_percentile": pct_is,
        "hf_beats_random": bool(hf_beats_random), "input_redundant": bool(input_redundant),
        "mirror_ok": bool(mirror_ok), "artifact_fraction": artifact_fraction,
    }


def write_memo(path, rungs, results, head, vd):
    L = []
    L.append("# Input-space vs Hazard-space Coverage — Findings\n")
    L.append(f"_Decision-gating diagnostic. Generated by "
             f"`scripts/supplemental/diagnose_input_vs_hazard_coverage.py`._\n")
    jr = vd["judged_rung"]
    hn = head[jr]["headline_n"]
    L.append("## Verdict\n")
    L.append(f"**The premise {vd['verdict']}** — judged at the fair-test `{jr}` (enriched) rung, N={hn}.\n")
    L.append(f"- **Hazard-space discrepancy ratio (input-stratified / hazard-filling): "
             f"{vd['discrepancy_ratio']:.2f}×** (>1 means input-space LHS covers hazard space worse).")
    L.append(f"- **Coverage in context** (percentile vs random designs at matched N; lower = more "
             f"uniform): hazard-filling **{vd['hazard_filling_percentile']:.2f}**, "
             f"input-stratified **{vd['input_stratified_percentile']:.2f}**. "
             f"Hazard-filling reliably beats random ({'yes' if vd['hf_beats_random'] else 'no'}); "
             f"input-LHS is no better than random ({'yes' if vd['input_redundant'] else 'no'}).")
    L.append(f"- Mirror check (input-stratified wins in input space): "
             f"**{'yes' if vd['mirror_ok'] else 'no'}** — confirms the selectors work; the spaces differ.")
    if vd["artifact_fraction"] == vd["artifact_fraction"]:  # not NaN
        L.append(f"- **Input-poverty artifact:** the impoverished `mean_only` rung over-states the "
                 f"redundancy — enriching the input space with a variance axis removes "
                 f"~**{100*vd['artifact_fraction']:.0f}%** of the excess discrepancy gap "
                 f"({head['mean_only']['hazard_l2_ratio_input_over_hazfill']:.2f}× → "
                 f"{head['mean_var']['hazard_l2_ratio_input_over_hazfill']:.2f}×).")
    L.append("")
    L.append("**Bottom line.** Subsampling directly in hazard space produces materially more uniform "
             "hazard coverage than space-filling in input (generator-parameter) space, and the "
             "advantage *survives* enriching the input space — so it is a real mechanism, not purely "
             "an artifact of a mean-only input space. The magnitude is **moderate** under a fair "
             "(mean+variance) input space (the dramatic redundancy seen with a mean-only input space "
             "is largely an artifact). Hazard-filling is justified for the campaign; its benefit "
             "should be framed against an *enriched* input-space baseline, not the mean-only strawman.\n")
    L.append("_ESS note: the kernel effective-sample-size (below) separates the designs clearly when "
             "redundancy is strong (the `mean_only` rung) but only weakly when it is moderate (the "
             "enriched rung), because in 4-D mild non-uniformity is captured far more sharply by "
             "L2-star discrepancy; read ESS as corroborating, with discrepancy as primary._\n")

    L.append("## Method (fair test)\n")
    L.append("- Same LHS+nearest-neighbor selector in all three designs; only the *space* differs "
             "(input theta vs the 4 fixed hazard axes vs random). All subsets drawn from the SAME "
             "theta-spanning master, so coverage differences isolate the selection criterion.\n")
    L.append(f"- Fixed hazard axes: {', '.join(FIXED_AXES)}.\n")
    L.append(f"- Richness ladder: " + ", ".join(
        f"`{r}` (N_master={rungs[r]['n_master']})" for r in rungs) + ".\n")

    L.append("## Headline numbers per rung (hazard space, at headline N)\n")
    L.append("Discrepancy percentile = fraction of random designs at matched N that this design beats "
             "on L2-star (lower = more uniform than chance).\n")
    L.append("| rung | N | L2 ratio (input/hazfill) | hazfill pctile | input pctile | hazfill ESS | input ESS |")
    L.append("|---|---|---|---|---|---|---|")
    for r, h in head.items():
        L.append(f"| {r} | {h['headline_n']} | {h['hazard_l2_ratio_input_over_hazfill']:.2f} | "
                 f"{h['hazard_pctile_hazard_filling']:.2f} | {h['hazard_pctile_input_stratified']:.2f} | "
                 f"{h['hazard_ess_hazard_filling']:.1f} | {h['hazard_ess_input_stratified']:.1f} |")
    L.append("")

    L.append("## Hazard-axis reachability from input space (max |Spearman|)\n")
    L.append("Low values mark forcing-limited axes the input space barely moves "
             "(cannot fairly be called 'uncovered by input sampling').\n")
    L.append("| axis | " + " | ".join(rungs) + " |")
    L.append("|---|" + "|".join(["---"] * len(rungs)) + "|")
    for axis in FIXED_AXES:
        row = [axis] + [f"{results[r]['reachability'][axis]['max_abs_spearman']:.2f}" for r in rungs]
        L.append("| " + " | ".join(row) + " |")
    L.append("")

    L.append("## Coverage vs N (hazard space, mean over seeds)\n")
    for r in rungs:
        L.append(f"### {r}\n")
        by_n = results[r]["coverage"]["spaces"]["hazard"]["by_n"]
        L.append("| N | design | L2-star | NN-CV | MST | ESS | disc. pctile |")
        L.append("|---|---|---|---|---|---|---|")
        for n in sorted(by_n):
            for design in DESIGNS:
                d = by_n[n][design]
                L.append(f"| {n} | {design} | {d['l2_star_mean']:.4f} | {d['nn_cv_mean']:.2f} | "
                         f"{d['mst_mean_mean']:.3f} | {d['ess_mean']:.1f} | "
                         f"{d['discrepancy_percentile_mean']:.2f} |")
        L.append("")

    L.append("## Caveats\n")
    L.append("- 5-yr realizations truncate the ~4–5-yr DRB drought of record, limiting "
             "multi-year drought-duration coverage; duration-type axes may read forcing-limited.")
    L.append("- No persistence or daily-extreme/flood-intensity forcing axis this round (deferred); "
             "the input space spans CMIP6 mean + an independent CV (variance) axis.")
    L.append("- Coverage is evaluated in empirical-CDF-normalized space; the input-stratified "
             "selector uses min-max normalization, so evaluation is independent of selection scaling.\n")
    Path(path).write_text("\n".join(L), encoding="utf-8")


# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------

def main() -> None:
    smoke = os.environ.get("NYCOPT_SMOKE") == "1"
    n_profiles = 24 if smoke else int(os.environ.get("NYCOPT_NPROFILES", "1000"))
    slugs = {
        "mean_only": f"kn_inputlhs_meanonly_{REALIZATION_YEARS}yr_n{n_profiles}",
        "mean_var": f"kn_inputlhs_meanvar_{REALIZATION_YEARS}yr_n{n_profiles}",
    }

    hist = load_historical_flows(gage=False, period="full")
    reference_daily = hist.loc[:, list(DEFAULT_NYC_INFLOW_NODES)].sum(axis=1)
    reference_monthly = daily_to_monthly(reference_daily, agg="mean")
    reference_daily = reference_daily.to_numpy(dtype=float)

    rungs, results = {}, {}
    for name, slug in slugs.items():
        print(f"[diag] loading rung '{name}' ({slug})...")
        rung = load_rung(slug, reference_monthly, reference_daily)
        rungs[name] = rung
        print(f"[diag] analyzing rung '{name}' (M={rung['n_master']})...")
        results[name] = {
            "slug": slug,
            "coverage": analyze_rung(rung),
            "reachability": reachability(rung),
        }

    head = compute_headline(results, rungs)
    vd = verdict(head, results, rungs)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    payload = {
        "fixed_axes": list(FIXED_AXES),
        "n_sweep": list(N_SWEEP),
        "subset_seeds": list(SUBSET_SEEDS),
        "rungs": {n: {"slug": results[n]["slug"], "n_master": rungs[n]["n_master"]} for n in rungs},
        "results": results,
        "headline": head,
        "verdict": vd,
    }
    (OUT_DIR / "results.json").write_text(json.dumps(payload, indent=2, default=float))
    print(f"[diag] wrote {OUT_DIR / 'results.json'}")

    print("[diag] building figures...")
    from src.plotting import style
    style.apply_style()
    make_figures(rungs, results, style, OUT_DIR / "figures")

    write_memo(OUT_DIR / "FINDINGS.md", rungs, results, head, vd)
    print(f"[diag] wrote {OUT_DIR / 'FINDINGS.md'}")
    print(f"[diag] VERDICT: premise {vd['verdict']} "
          f"(discrepancy_ratio={vd['discrepancy_ratio']:.2f}, "
          f"hazfill_pctile={vd['hazard_filling_percentile']:.2f}, "
          f"input_pctile={vd['input_stratified_percentile']:.2f})")


if __name__ == "__main__":
    main()
