"""verify_prefix_identity.py - Assert the prefix contract of the nested-P design.

The nested-P saturation ladder scores each rung P' on the first P' rows of one
large staged hazard image, on the claim that realizations are keyed to a GLOBAL
index with per-realization child streams, so a prefix is bit-identical to a
standalone i.i.d. pool of the same size from the same seed domain. This checks
that claim directly: the standalone P=2,000 smoke pool and the large pool were
generated by separate jobs, so row-for-row equality of their hazard images is an
end-to-end verification (generation -> hazard metrics -> persisted image).

All configuration is via environment variables (no CLI value flags):

    NYCOPT_NESTEDP_POOL_SLUG   the large pool's staged slug (required)
    NYCOPT_NESTEDP_SMOKE_SLUG  the standalone smoke pool's slug
                               (default statpool_10yr_n2000_d0)

Exits nonzero on any mismatch — the ladder must not run on a broken contract.
"""

from __future__ import annotations

import os
import sys
from pathlib import Path

PROJECT_DIR = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(PROJECT_DIR))

import numpy as np  # noqa: E402

import config  # noqa: E402
from scengen.diagnostics import load_hazard_image  # noqa: E402

POOL_SLUG = os.environ["NYCOPT_NESTEDP_POOL_SLUG"]
SMOKE_SLUG = os.environ.get("NYCOPT_NESTEDP_SMOKE_SLUG", "statpool_10yr_n2000_d0")


def main() -> None:
    """Compare the smoke pool's image to the large pool's leading rows."""
    big = load_hazard_image(config.STAGED_ENSEMBLE_DIR / POOL_SLUG / "hazard_image.npz")
    smoke = load_hazard_image(
        config.STAGED_ENSEMBLE_DIR / SMOKE_SLUG / "hazard_image.npz"
    )
    n = len(smoke["H"])
    if list(big["hazard_axes"]) != list(smoke["hazard_axes"]):
        raise SystemExit(
            f"[verify_prefix] axis mismatch: {big['hazard_axes']} vs "
            f"{smoke['hazard_axes']}"
        )
    if not np.array_equal(big["H"][:n], smoke["H"]):
        diff = np.abs(big["H"][:n] - smoke["H"])
        raise SystemExit(
            f"[verify_prefix] FAILED: first {n} rows of '{POOL_SLUG}' differ from "
            f"standalone '{SMOKE_SLUG}' (max abs diff {np.nanmax(diff):.3e}, "
            f"{int((diff > 0).any(axis=1).sum())} rows differ). The prefix "
            f"contract does not hold — do not run the ladder."
        )
    print(f"[verify_prefix] OK: first {n} rows of '{POOL_SLUG}' are bit-identical "
          f"to standalone '{SMOKE_SLUG}' ({big['H'].shape[1]} axes).")


if __name__ == "__main__":
    main()
