"""local_test_ensemble.py - A small stationary ensemble for local work.

A fixed **5-realization x 50-year stationary Kirsch-Nowak** ensemble, staged
once under ``config.STAGED_ENSEMBLE_DIR`` and reused by any local experiment,
figure script, or test that needs a real multi-realization ensemble without an
HPC generation run. It is deliberately tiny (5 realizations) so a two-policy
comparison simulates in a couple of minutes on a laptop, and stationary (no
deeply-uncertain forcing) so it exercises the ensemble-evaluation path on
plain probabilistic streamflow.

Usage::

    from src.local_test_ensemble import ensure_local_test_ensemble
    spec = ensure_local_test_ensemble()      # generate+stage on first call, else reuse
    # spec is a ready-to-simulate EnsembleSpec (is_ensemble=True, 5 realizations)

The ensemble resolves anywhere by its slug through the ``kn_{Y}yr_n{N}`` grammar
(``config`` / ``src.ensembles.get_ensemble_spec``), so code that already takes a
preset name can use ``LOCAL_TEST_ENSEMBLE_SLUG`` directly with no import of this
module.

This is a LOCAL fixture, not a campaign artifact: the manuscript ensembles are
sized and generated by the main workflow (steps 02-04). Keep it small.
"""

from __future__ import annotations

import os

#: Ensemble shape. Small and stationary by design (see module docstring).
LOCAL_TEST_N_REALIZATIONS: int = 5
LOCAL_TEST_REALIZATION_YEARS: int = 50
#: Kirsch-Nowak generation seed (the project-wide KN seed; distinct from any DV seed).
LOCAL_TEST_KN_SEED: int = 1234

#: Canonical ``kn_{Y}yr_n{N}`` slug. Resolves via the slug grammar with no registry entry.
LOCAL_TEST_ENSEMBLE_SLUG: str = (
    f"kn_{LOCAL_TEST_REALIZATION_YEARS}yr_n{LOCAL_TEST_N_REALIZATIONS}"
)


def ensure_local_test_ensemble(*, force: bool = False, verbose: bool = True):
    """Generate + stage the local test ensemble if needed, and return its spec.

    Idempotent: if the ensemble is already fully staged (all
    :data:`~src.ensembles.STAGED_ENSEMBLE_FILES` present and non-empty) and
    ``force`` is ``False``, this only resolves and returns the spec without any
    simulation or file I/O. Otherwise it runs the Step-1 Kirsch-Nowak generator
    (when the base inflows are missing) and the Step-3 pywrdrb preprocessors
    (flood-node inflows, STARFIT presim releases, predicted inflows).

    Salinity and temperature LSTMs are forced off for the run (via
    ``os.environ.setdefault`` before ``config`` is imported): the ensemble
    objective set uses neither, and disabling them is a large speedup. Callers
    that go on to *simulate* on this ensemble should likewise ensure those knobs
    are off before importing ``config`` (see
    ``supplemental_config.configure_ensemble_env``).

    Args:
        force: Regenerate and re-stage even if the ensemble already exists.
        verbose: Print progress. Generation/staging themselves print regardless.

    Returns:
        The staged ensemble's :class:`~src.ensembles.EnsembleSpec`
        (``is_ensemble=True``, ``LOCAL_TEST_N_REALIZATIONS`` realizations).
    """
    # Must precede any import that triggers ``config`` (it reads these at import).
    os.environ.setdefault("NYCOPT_SALINITY_ON", "0")
    os.environ.setdefault("NYCOPT_TEMPERATURE_ON", "0")

    from src.ensembles import (
        get_ensemble_spec,
        staged_ensemble_dir,
        staged_ensemble_missing,
    )

    slug = LOCAL_TEST_ENSEMBLE_SLUG

    if not force and not staged_ensemble_missing(slug):
        if verbose:
            print(f"[local_test_ensemble] '{slug}' already staged; reusing.")
        return get_ensemble_spec(slug)

    from src.ensemble_generation import generate_kirsch_nowak_ensemble
    from src.ensemble_prep import stage_pywrdrb_ensemble_inputs

    flows_dir = staged_ensemble_dir(slug)
    flows_dir.mkdir(parents=True, exist_ok=True)
    base_inflow = flows_dir / "catchment_inflow_mgd.hdf5"

    if force or not base_inflow.exists():
        if verbose:
            print(
                f"[local_test_ensemble] generating '{slug}' "
                f"(N={LOCAL_TEST_N_REALIZATIONS}, {LOCAL_TEST_REALIZATION_YEARS}-yr, "
                f"seed={LOCAL_TEST_KN_SEED}) ..."
            )
        generate_kirsch_nowak_ensemble(
            n_years=LOCAL_TEST_REALIZATION_YEARS,
            n_realizations=LOCAL_TEST_N_REALIZATIONS,
            seed=LOCAL_TEST_KN_SEED,
            output_dir=flows_dir,
        )

    spec = get_ensemble_spec(slug)
    stage_pywrdrb_ensemble_inputs(spec, force=force)

    if verbose:
        missing = staged_ensemble_missing(slug)
        status = "fully staged" if not missing else f"MISSING {missing}"
        print(f"[local_test_ensemble] '{slug}' {status}.")
    return spec


if __name__ == "__main__":
    ensure_local_test_ensemble()
